package surfwords

import (
  "math/rand"
)

func Words() string{
  wordList := []string {
    "A-frame",
    "Aggro",
    "Air",
    "Alaia",
    "Aloha",
    "Amped",
    "Ankle slappers",
    "Backdoor",
    "Backside",
    "Backwash",
    "Bail",
    "Barney",
    "Beach break",
    "Bitchin'",
    "Bomb",
    "Blank",
    "Bottom turn",
    "Bogging",
    "Break",
    "Brah",
    "Bro",
    "Burn",
    "Carve",
    "Caught inside",
    "Charging",
    "Chop",
    "Choppy",
    "Clean",
    "Closeout",
    "Cowabunga",
    "Crest",
    "Curl",
    "Cutback",
    "Dawn patrol",
    "Deck",
    "Dick dragger",
    "Ding",
    "Drop",
    "Drop-in",
    "Duck diving",
    "Dude",
    "Fin",
    "Fish",
    "Fish tail",
    "Firing",
    "Flat",
    "Floater",
    "Foam",
    "Frontside",
    "Froth",
    "Funboard",
    "Glassy",
    "Greenroom",
    "Gnarly",
    "Goofy footed",
    "Grom",
    "Gun",
    "Hang five",
    "Hang loose",
    "Hang ten",
    "Haole",
    "Hawaiian",
    "Heavy",
    "Hit the lip",
    "Hollow",
    "Inside",
    "Kahuna",
    "Kickout",
    "Kook",
    "Layback",
    "Leash",
    "Left",
    "Leg rope",
    "Line-up",
    "Lines",
    "Lip",
    "Local",
    "Localism",
    "Log",
    "Longboard",
    "Lull",
    "Making-the-drop",
    "Men in the grey suits",
    "Messy",
    "Mini simmons",
    "Mush",
    "Mushy",
    "Noodle arms",
    "Nose",
    "Nose riding",
    "Nug",
    "Off the lip",
    "Off the wall",
    "Offshore",
    "Onshore",
    "Outside",
    "Outside break",
    "Out the back",
    "Over the falls",
    "Overhead",
    "Paddle",
    "Paddle battle",
    "Party wave",
    "Peak",
    "Pearl",
    "Peeling",
    "Pig dog",
    "Pintail",
    "Pit",
    "Pitted",
    "Pocket",
    "Pointbreak",
    "Pop up",
    "Pull in",
    "Pumping",
    "Quad",
    "Quiver",
    "Rad",
    "Radical",
    "Rails",
    "Rashguard",
    "Re-entry",
    "Reef break",
    "Regular footed",
    "Right",
    "Rip",
    "Rip current",
    "Riptide",
    "Rocker",
    "Rogue wave",
    "Section",
    "Set",
    "Shacked",
    "Shaka",
    "Shape",
    "Shaper",
    "Shore",
    "Shore break",
    "Shortboard",
    "Shoulder",
    "Shred",
    "Shubie",
    "Sick",
    "Single fin",
    "Sketchy",
    "Slab",
    "Slotted",
    "Snake",
    "Soft top",
    "Soup",
    "Spat out",
    "Spit",
    "Sponge",
    "Stall",
    "Stick",
    "Stoked",
    "Stringer",
    "Sucking dry",
    "Surf camp",
    "Swell",
    "Tail",
    "Take-off",
    "Thruster",
    "Tombstoning",
    "Tow in",
    "Trough",
    "Tube",
    "Tubular",
    "Turtle roll",
    "Twin fin",
    "Wall",
    "Washing machine",
    "Wave",
    "Wax",
    "Wetsuit",
    "White water",
    "Wipeout",
    "Worked",
  }

  return wordList[rand.Intn(len(wordList))]
}
